replicaCount: 2

image:
  repository: flask-k8s-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env:
  APP_VERSION: "1.0.0"
  POD_NAMESPACE: "flask-app"